### ISSUE TITLE
Invited member's role is not respected when joining workspace

### ISSUE THREAD

**Issue by vhpx** [tutur3u/tutur3u#872]

**Comment by RANJEETJ06** [comment]
Create a .env file with your database URL and other secrets (ask a maintainer for an example)

plz tell me about this for local setup

**Comment by vhpx** [comment]
# Local setup

You can create a `.env.local` file at the root of your project and put in the following values:

```env
NEXT_PUBLIC_SUPABASE_URL=YOUR_SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=YOUR_SUPABASE_ANON_KEY
SUPABASE_SERVICE_KEY=YOUR_SUPABASE_SERVICE_KEY
```

- For Supabase local cli setup, please see [this link](https://supabase.com/docs/reference/cli/supabase-init).
- For Tuturuuu local setup, please follow the project's [README](https://github.com/tutur3u/tutur3u/blob/main/README.md).

## Notice

> Please create a new issue if you need extra help on Tuturuuu, since this issue is focused on something else.
